import React from 'react';
// eslint-disable-next-line 
import Box from '@mui/material/Box';
// eslint-disable-next-line 
import Paper from '@mui/material/Grid';
import Grid from '@mui/material/Grid';
import Avatar from '@mui/material/Avatar';
import miFoto from '../../assets/miFoto.png';




const AboutMe = () => {
    return (
        <>

<Box minHeight="85vh">
      <Grid justifyContent="left" container padding={2} spacing={2}>

        <Grid item xs={6} md={2}>
        <Avatar alt="picture of me" src={miFoto} sx={{ width: 1, height: 1}}></Avatar>
        </Grid>

        <Grid item xs={6} md={2}>
        <h1>Connor Banks</h1>
        <p>~Whale Noises~</p>
        <p>AIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUA</p>
        <p>AIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUA</p>
        <p>AIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUA</p>
        <p>AIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUA</p>
        <p>AIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUA</p>
        <p>AIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUA</p>
        <p>AIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUA</p>
        <p>AIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUA</p>
        <p>AIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUA</p>
        <p>AIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUA</p>
        </Grid>

        </Grid>
        </Box>
        </>
    )
}

export default AboutMe 