import React from 'react'
import Grid from '@mui/material/Grid';

const MyWork = () => {
  return (
<>
        
    <Grid container justifyContent="left">
    <h1>My Portfolio</h1>
    <p>~Whale Noises~</p>
        <p>AIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUA</p>
        <p>AIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUA</p>
        <p>AIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUA</p>
        <p>AIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUA</p>
        <p>AIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUA</p>
        <p>AIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUA</p>
        <p>AIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUA</p>
        <p>AIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUA</p>
        <p>AIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUA</p>
        <p>AIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUAAIAAIEEAEEOUUEEEEAEEEEAAUUAIIEEIIUUEEAOAEEIAEEEEOUUEEIEEIEEOOEEOAUUA</p>
        <Grid item xs={10} md={4}>
    
        </Grid>
    </Grid>

</>
  )
}

export default MyWork



